import os
import re
from pathlib import Path

NOTES_DIR = "/home/jorg/stacks/remastered_bot/notebook/Research_Notes"

def rescue_files():
    notes_dir = Path(NOTES_DIR)
    md_files = list(notes_dir.rglob("*.md"))
    
    print(f"Found {len(md_files)} files. Fixing names and asset links...")
    
    for md_file in md_files:
        with open(md_file, 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Find the NEW_FILENAME tag generated by DeepSeek
        new_name_match = re.search(r"NEW_FILENAME:\s*([^\n]+)", content)
        if not new_name_match:
            continue
            
        raw_new_name = new_name_match.group(1).strip()
        # Clean the name (lowercase, underscores only)
        clean_name = re.sub(r'[^a-z0-9_]', '', raw_new_name.lower().replace(" ", "_"))
        
        if not clean_name or clean_name == md_file.stem:
            continue
            
        new_md_name = f"{clean_name}.md"
        new_md_path = md_file.parent / new_md_name
        
        old_stem = md_file.stem
        old_assets_dir = md_file.parent / f"{old_stem}_assets"
        new_assets_dir = md_file.parent / f"{clean_name}_assets"
        
        print(f"Renaming: {old_stem} -> {clean_name}")
        
        # 1. Rename the assets folder if it exists
        if old_assets_dir.exists():
            os.rename(old_assets_dir, new_assets_dir)
            
        # 2. Update the image links in the markdown content
        updated_content = content.replace(f"{old_stem}_assets/", f"{clean_name}_assets/")
        
        # 3. Save the updated content to the new file
        with open(new_md_path, 'w', encoding='utf-8') as f:
            f.write(updated_content)
            
        # 4. Delete the old markdown file
        md_file.unlink()
        
    print("Rescue complete! All files and asset links are fixed.")

if __name__ == "__main__":
    rescue_files()
